baseurl = "https://halink0803.github.io/"
languageCode = "vi-vn"
title = "Ha Link's Space"
theme = "casper"
DisqusShortname = "halink-space"
publishDir = "./"
canonifyurls = true
paginate = 5
RSSLink = "http://eepurl.com/cw3xgj"


[[menu.main]]
	identifier = "blog"
	name 	= "Home"
	url 	= "/"
	weight	= "-120"

[[menu.main]]
	identifier 	= "about"
	name	= "About"
	url		= "/about"
	weight	= "-110"

[[menu.main]]
	identifier = "100-days-of-code"
	name 	= "100 days of code"
	url		= "/100-days-of-code"
	weight 	= "-100"

[params]
	cover = "images/cover.jpg"
	logo = "images/logo.png"
	author = "Ha Link"
	authorlocation = "Hanoi, Vietnam"
	authorwebsite = "http://halink.space"
	googleAnalyticsUserID = "UA-85056815-1"
	githubName = "halink0803"
	# twitterName = "halink0803"
	facebookName = "halink0803"
	linkedinName = "halink0803"
	RSSLink = "http://eepurl.com/cw3xgj"

